# -*- coding: utf-8 -*-
"""PDF_Query.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C4P7p7n1SQlJq-RX2vpA5Kl_ltavYfVa
"""

import os
import openai
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain import OpenAI, VectorDBQA
from langchain.document_loaders import UnstructuredFileLoader
from langchain.text_splitter import CharacterTextSplitter
import nltk

# Download the Punkt tokenizer data if not already downloaded
nltk.download("punkt")

# Set your OpenAI API key here
os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_API_KEY"

# Load PDF
def load_pdf(pdf_file_path, mode='full'):
    loader = UnstructuredFileLoader(pdf_file_path, mode=mode)
    documents = loader.load()
    return documents

# Split Documents Into Chunks
def split_documents_into_chunks(documents, chunk_size=800, chunk_overlap=0):
    text_splitter = CharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    texts = text_splitter.split_documents(documents)
    return texts

# Prepare Model And Embeddings
def prepare_model_and_embeddings(texts):
    embeddings = OpenAIEmbeddings(openai_api_key=os.environ['OPENAI_API_KEY'])
    doc_search = Chroma.from_documents(texts, embeddings)
    chain = VectorDBQA.from_chain_type(llm=OpenAI(), chain_type="stuff", vectorstore=doc_search)
    return chain

# Create Query And Get Response
def query_document(chain, query):
    response = chain.run(query)
    return response

if __name__ == "__main__":
    # Replace 'SamplePDF.pdf' with the path to your PDF file
    pdf_file_path = '/content/SE_notes.pdf'

    # Load PDF documents
    documents = load_pdf(pdf_file_path,mode='paged')

    # Split documents into chunks
    texts = split_documents_into_chunks(documents)

    # Prepare model and embeddings
    chain = prepare_model_and_embeddings(texts)

    # Create a query
    query = input("enter your query")

    # Get a response
    response = query_document(chain, query)

    # Print the response
    print(response)